### ISSUE TITLE
在Windows Sandbox中无效

### ISSUE THREAD

**Issue by krishukr** [xiaoyv404/NeteaseMusic-Unlocker#2]
## 环境
- Windows 10 2004 Enterprise 64位

- NeteaseMusic-Unlocker 1.0

- 网易云音乐 2.7.1

- 7-zip 19.00

## 简述
- 未自动在网易云音乐中添加代理

![pwq](https://s1.ax1x.com/2020/07/30/aK4DW4.png)

## 重现

> 若无其他说明，安装位置默认

1. 打开Windows Sandbox

2. 安装7-zip

3. 安装网易云音乐

4. 运行脚本

5. 发现脚本无效

已在QQ向作者反馈，仅为记录

**Comment by xiaoyv404** [comment]
收到bug，正在捉虫

**Comment by krishukr** [comment]
维护者在release里确认bug了
所以尽快修
![pwq](https://s1.ax1x.com/2020/07/30/aKIKPS.png)

**Comment by xiaoyv404** [comment]
别骂了null在努力了

**Comment by krishukr** [comment]
@xiaoyv404 
![?](https://s1.ax1x.com/2020/07/30/aKHcOH.jpg)

**Comment by xiaoyv404** [comment]
hhhhh

**Comment by krishukr** [comment]
好像修好了

**Comment by krishukr** [comment]
已确认修好，作者大大牛逼
