### ISSUE TITLE
桌面快捷方式修改失败

### ISSUE THREAD

**Issue by xiaoyv404** [xiaoyv404/NeteaseMusic-Unlocker#7]
## 环境
- windows 10 专业版 2004
- 对桌面地址做了修改，地址为D:\Users\Administrator\Desktop
- 对网易云地址做了修改，地址为D:\Program Files (x86)\Netease\CloudMusic
## 出现bug
- 原快捷方式被删除，修改后的快捷方式未出现在桌面

**Comment by NULL204** [comment]
以收到bug，正在全力修复

**Comment by NULL204** [comment]
已修复此问题
