### ISSUE TITLE
1.3版本在2.7.3版本的网易云音乐上运行后并没有自动设置代理

### ISSUE THREAD

**Issue by aLIEz-xue** [xiaoyv404/NeteaseMusic-Unlocker#8]
系统为
![image](https://user-images.githubusercontent.com/59567929/90464285-88a62300-e13f-11ea-83bf-8da5bf4431d5.png)
网易云音乐
![image](https://user-images.githubusercontent.com/59567929/90464327-a07da700-e13f-11ea-92d8-57e78fbbd57e.png)
开始部署后对话框为
![image](https://user-images.githubusercontent.com/59567929/90464373-be4b0c00-e13f-11ea-9167-4e43f7c6ff01.png)

**Comment by NULL204** [comment]
已收到BUG,抱歉，这是逻辑上的疏漏，我会在今天之内修复BUG

**Comment by NULL204** [comment]
BUG已修复，请检查，谢谢支持

**Comment by aLIEz-xue** [comment]
测试可用，感谢
